language: java
jdk: oraclejdk8
dist: trusty

env:
  global:
    travis encrypt DOCKER_USER=”dockerhub-username”
    travis encrypt DOCKER_PASS=”dockerhub-password”


sudo: required

services:
  - docker

script:
  - mvn clean install -B

deploy:
  provider: heroku
  api_key: 8a8737bf-174b-46d8-a116-23ac58a70e69
  app: sunnyoks-application.book-store